apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-limits
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: banking
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated:    
  source:
    path: banking/limits
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}